### ISSUE TITLE
Some Home Assistant functions are deprecated

### ISSUE THREAD

**Issue by jurrianv** [garbled1/pybalboa#3]
Hi,

I'm using Home Assistant 0.111.4 and I get the following messages in my logs:

- ClimateDevice is deprecated, modify BalboaSpaClimate to extend ClimateEntity
- SwitchDevice is deprecated, modify BalboaSpaSwitch to extend SwitchEntity
- BinarySensorDevice is deprecated, modify BalboaSpaBinarySensor to extend BinarySensorEntity

Is it possible to fix this for the future release?

Thanks!

**Comment by garbled1** [comment]
Yeah.. I'll have to go look at the changes and see what needs to be done.  Thanks!

**Comment by jurrianv** [comment]
Great. Thanks for your help.

**Comment by garbled1** [comment]
This is fixed in 0.5 of the component.
