### ISSUE TITLE
Can't find my Blower

### ISSUE THREAD

**Issue by superentwickler** [garbled1/pybalboa#34]
Hello, I have also a Blower in my Jacuzzi, but I can't find it in the controls.

******** Testing spa connection and configuration **********

Module identification
---------------------
MAC address: 00:15:27:e4:00:9d
iDigi Device Id: 00000000-00000000-001527FF-FFE4009D

Device configuration
--------------------
Circulation pump: OFF
Pumps: ['Pump 1']
Lights: ['Light 1']
Aux: []
Blower: ['Blower 1']
Mister: []

System information
------------------
Model: BP6013G1
Software version: M100_226 V43.0
Configuration signature: 1b456746
Current setup: 4
Voltage: None
Heater type: standard
DIP switch: 0000001000000000

Setup parameters
----------------
Min temps: ((50, 99), (10.0, 37.0))
Max temps: ((80, 104), (26.5, 40.0))
# of pumps: 1

Filter cycle
------------
Filter cycle 1 start: 03:00:00
Filter cycle 1 duration: 2:00:00
Filter cycle 2 start: 14:00:00 (enabled)
Filter cycle 2 duration: 2:00:00

Status update
-------------
Temperature unit: CELSIUS
Temperature: None
Target temperature: 32.5
Temperature range: LOW
Heat mode: REST
Heat state: OFF
Pump status: [Pump 1: OFF]
Circulation pump: OFF
Light status: [Light 1: ON]
Mister status: []
Aux status: []
Blower status: [Blower 1: UNKNOWN]
Spa time: 02:54 24hr
Filter cycle 1 running: False
Filter cycle 2 running: False

**Comment by natekspencer** [comment]
Can you enable debugging and post the full debug logs. It looks like it is picking up that there is a blower, but can't resolve the state of it.

**Comment by superentwickler** [comment]
no problem

DEBUG:asyncio:Using selector: EpollSelector
******** Testing spa connection and configuration **********
DEBUG:pybalboa.client:10.10.78.100 -- establishing connection
DEBUG:pybalboa.client:10.10.78.100 -- connected
DEBUG:pybalboa.client:10.10.78.100 <- DEVICE_PRESENT: 050abf0477
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_SYSTEM_INFORMATION: 080abf2202000089
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_SETUP_PARAMETERS: 080abf22040000f4
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_DEVICE_CONFIGURATION: 080abf2200000158
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_FILTER_CYCLE: 080abf2201000034
DEBUG:pybalboa.client:10.10.78.100 -> MODULE_IDENTIFICATION: 1e0abf94021480001527e4009d0000000000000000001527ffffe4009d8d
DEBUG:pybalboa.client:10.10.78.100 -> SYSTEM_INFORMATION: 1a0abf2464e22b004250363031334731041b456746030a020003
DEBUG:pybalboa.client:10.10.78.100 -> SETUP_PARAMETERS: 0f0abf2509043263506841014102f8
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d23002803060304000000030000000202490000001e000058
DEBUG:pybalboa.control:10.10.78.100 -- Temperature range is now HIGH (1)
DEBUG:pybalboa.control:10.10.78.100 -- Heat mode is now READY (0)
DEBUG:pybalboa.client:10.10.78.100 -> DEVICE_CONFIGURATION: 0b0abf2e0100019100006d
DEBUG:pybalboa.client:10.10.78.100 -> FILTER_CYCLE: 0d0abf23030002008e000200e3
DEBUG:pybalboa.control:10.10.78.100 -- Light 1 is now ON (1)
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now OFF (0)
DEBUG:pybalboa.control:10.10.78.100 -- Circulation pump is now OFF (0)

Module identification
---------------------
MAC address: 00:15:27:e4:00:9d
iDigi Device Id: 00000000-00000000-001527FF-FFE4009D

Device configuration
--------------------
Circulation pump: OFF
Pumps: ['Pump 1']
Lights: ['Light 1']
Aux: []
Blower: ['Blower 1']
Mister: []

System information
------------------
Model: BP6013G1
Software version: M100_226 V43.0
Configuration signature: 1b456746
Current setup: 4
Voltage: None
Heater type: standard
DIP switch: 0000001000000000

Setup parameters
----------------
Min temps: ((50, 99), (10.0, 37.0))
Max temps: ((80, 104), (26.5, 40.0))
# of pumps: 1

Filter cycle
------------
Filter cycle 1 start: 03:00:00
Filter cycle 1 duration: 2:00:00
Filter cycle 2 start: 14:00:00 (enabled)
Filter cycle 2 duration: 2:00:00

Status update
-------------
Temperature unit: CELSIUS
Temperature: 36.5
Target temperature: 36.5
Temperature range: HIGH
Heat mode: READY
Heat state: OFF
Pump status: [Pump 1: OFF]
Circulation pump: OFF
Light status: [Light 1: ON]
Mister status: []
Aux status: []
Blower status: [Blower 1: UNKNOWN]
Spa time: 13:35 24hr
Filter cycle 1 running: False
Filter cycle 2 running: False

******** Testing spa controls **********

Temperature control
-------------------
Current target temperature: 36.5
  Set to 40.0
DEBUG:pybalboa.client:10.10.78.100 <- SET_TEMPERATURE: 060abf2050a5
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002030000000202500000001e000003
DEBUG:pybalboa.control:10.10.78.100 -- Circulation pump is now ON (1)
  Set temperature is now 40.0
Current target temperature: 40.0
  Set to 36.5
DEBUG:pybalboa.client:10.10.78.100 <- SET_TEMPERATURE: 060abf2049ea
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002030000000202490000001e0000e5
  Set temperature is now 36.5

Heat mode control
-----------------
Current state: READY
  Set to REST
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf11514e
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2301280306030c0000020300000002024900000000000039
DEBUG:pybalboa.control:10.10.78.100 -- Heat mode is now REST (1)
  State is now REST
Current state: REST
  Set to READY
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf11514e
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002030000000202490000001e0000e5
DEBUG:pybalboa.control:10.10.78.100 -- Heat mode is now READY (0)
  State is now READY

Temperature range control
-------------------------
Current state: HIGH
  Set to LOW
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf115049
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d23002803060308000002030000000202410000001e000037
DEBUG:pybalboa.control:10.10.78.100 -- Temperature range is now LOW (0)
  State is now LOW
Current state: LOW
  Set to HIGH
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf115049
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002030000000202490000001e0000e5
DEBUG:pybalboa.control:10.10.78.100 -- Temperature range is now HIGH (1)
  State is now HIGH

Pump 1 control
--------------
Current state: OFF
  Set to ON
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf1104e2
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c020002030000000202490000001e0000e1
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now ON (2)
  State is now ON
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf1104e2
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002030000000202490000001e0000e5
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now OFF (0)
  State is now OFF

Light 1 control
---------------
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf111189
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002000000000202490000001e00005e
DEBUG:pybalboa.control:10.10.78.100 -- Light 1 is now OFF (0)
  State is now OFF
Current state: OFF
  Set to ON
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf111189
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2300280306030c000002030000000202490000001e0000e5
DEBUG:pybalboa.control:10.10.78.100 -- Light 1 is now ON (1)
  State is now ON

Circulation pump control
------------------------
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf113d4d
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c000002030000000202490000001e0000c3
  State was not changed after 10 seconds; is ON

Blower 1 control
----------------
Current state: UNKNOWN
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf110cda
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c00000e030000000202490000001e000063
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c02000e030000000202490000001e000067
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now ON (2)
  State was not changed after 10 seconds; is UNKNOWN
Current state: UNKNOWN
  Set to ON
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf110cda
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c020002030000000202490000001e0000c7
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c02000e030000000202490000001e000067
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c020002030000000202490000001e0000c7
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490d2400280306030c000002030000000202490000001e0000c3
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now OFF (0)
  State was not changed after 10 seconds; is UNKNOWN

DEBUG:pybalboa.client:10.10.78.100 -- disconnect requested
DEBUG:pybalboa.client:10.10.78.100 -- stopped listening
DEBUG:pybalboa.client:10.10.78.100 -- disconnected

**Comment by natekspencer** [comment]
Please update to 1.0.1 and try again. There was an error in setting the blower states. You should be able to find the blower control in `spa.blowers`

**Comment by superentwickler** [comment]
I updated and debuged again.

DEBUG:asyncio:Using selector: EpollSelector
******** Testing spa connection and configuration **********
DEBUG:pybalboa.client:10.10.78.100 -- establishing connection
DEBUG:pybalboa.client:10.10.78.100 -- connected
DEBUG:pybalboa.client:10.10.78.100 <- DEVICE_PRESENT: 050abf0477
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_SYSTEM_INFORMATION: 080abf2202000089
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_SETUP_PARAMETERS: 080abf22040000f4
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_DEVICE_CONFIGURATION: 080abf2200000158
DEBUG:pybalboa.client:10.10.78.100 <- REQUEST_FILTER_CYCLE: 080abf2201000034
DEBUG:pybalboa.client:10.10.78.100 -> MODULE_IDENTIFICATION: 1e0abf94021480001527e4009d0000000000000000001527ffffe4009d8d
DEBUG:pybalboa.client:10.10.78.100 -> SYSTEM_INFORMATION: 1a0abf2464e22b004250363031334731041b456746030a020003
DEBUG:pybalboa.client:10.10.78.100 -> SETUP_PARAMETERS: 0f0abf2509043263506841014102f8
DEBUG:pybalboa.client:10.10.78.100 -> DEVICE_CONFIGURATION: 0b0abf2e01000191006872
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b1c000002000000000202490000001e000041
DEBUG:pybalboa.control:10.10.78.100 -- Temperature range is now HIGH (1)
DEBUG:pybalboa.control:10.10.78.100 -- Light 1 is now OFF (0)
DEBUG:pybalboa.control:10.10.78.100 -- Heat mode is now READY (0)
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now OFF (0)
DEBUG:pybalboa.control:10.10.78.100 -- Circulation pump is now ON (1)
DEBUG:pybalboa.control:10.10.78.100 -- Blower 1 is now ON (1)
DEBUG:pybalboa.client:10.10.78.100 -> FILTER_CYCLE: 0d0abf23030002008e000200e3

Module identification
---------------------
MAC address: 00:15:27:e4:00:9d
iDigi Device Id: 00000000-00000000-001527FF-FFE4009D

Device configuration
--------------------
Circulation pump: ON
Pumps: ['Pump 1']
Lights: ['Light 1']
Aux: []
Blower: ['Blower 1']
Mister: []

System information
------------------
Model: BP6013G1
Software version: M100_226 V43.0
Configuration signature: 1b456746
Current setup: 4
Voltage: None
Heater type: standard
DIP switch: 0000001000000000

Setup parameters
----------------
Min temps: ((50, 99), (10.0, 37.0))
Max temps: ((80, 104), (26.5, 40.0))
# of pumps: 1

Filter cycle
------------
Filter cycle 1 start: 03:00:00
Filter cycle 1 duration: 2:00:00
Filter cycle 2 start: 14:00:00 (enabled)
Filter cycle 2 duration: 2:00:00

Status update
-------------
Temperature unit: CELSIUS
Temperature: 36.5
Target temperature: 36.5
Temperature range: HIGH
Heat mode: READY
Heat state: HEATING
Pump status: [Pump 1: OFF]
Circulation pump: ON
Light status: [Light 1: OFF]
Mister status: []
Aux status: []
Blower status: [Blower 1: ON]
Spa time: 14:20 24hr
Filter cycle 1 running: False
Filter cycle 2 running: True

******** Testing spa controls **********

Temperature control
-------------------
Current target temperature: 36.5
  Set to 40.0
DEBUG:pybalboa.client:10.10.78.100 <- SET_TEMPERATURE: 060abf2050a5
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b1c000002000000000202500000001e0000a7
  Set temperature is now 40.0
Current target temperature: 40.0
  Set to 36.5
DEBUG:pybalboa.client:10.10.78.100 <- SET_TEMPERATURE: 060abf2049ea
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b1c000002000000000202490000001e000041
  Set temperature is now 36.5

Heat mode control
-----------------
Current state: READY
  Set to REST
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf11514e
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14012803060b1c000002000000000202490000000000009d
DEBUG:pybalboa.control:10.10.78.100 -- Heat mode is now REST (1)
  State is now REST
Current state: REST
  Set to READY
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf11514e
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b1c000002000000000202490000001e000041
DEBUG:pybalboa.control:10.10.78.100 -- Heat mode is now READY (0)
  State is now READY

Temperature range control
-------------------------
Current state: HIGH
  Set to LOW
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf115049
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b08000002000000000202410000001e000073
DEBUG:pybalboa.control:10.10.78.100 -- Temperature range is now LOW (0)
  State is now LOW
Current state: LOW
  Set to HIGH
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf115049
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c000002000000000202490000001e0000a1
DEBUG:pybalboa.control:10.10.78.100 -- Temperature range is now HIGH (1)
  State is now HIGH

Pump 1 control
--------------
Current state: OFF
  Set to ON
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf1104e2
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c020002000000000202490000001e0000a5
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now ON (2)
  State is now ON
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf1104e2
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c000002000000000202490000001e0000a1
DEBUG:pybalboa.control:10.10.78.100 -- Pump 1 is now OFF (0)
  State is now OFF

Light 1 control
---------------
Current state: OFF
  Set to ON
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf111189
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c000002030000000202490000001e00001a
DEBUG:pybalboa.control:10.10.78.100 -- Light 1 is now ON (1)
  State is now ON
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf111189
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c000002000000000202490000001e0000a1
DEBUG:pybalboa.control:10.10.78.100 -- Light 1 is now OFF (0)
  State is now OFF

Circulation pump control
------------------------
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf113d4d
  State was not changed after 10 seconds; is ON

Blower 1 control
----------------
Current state: ON
  Set to OFF
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf110cda
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c00000e000000000202490000001e000001
DEBUG:pybalboa.control:10.10.78.100 -- Blower 1 is now UNKNOWN (3)
  State was not changed after 10 seconds; is UNKNOWN
Current state: UNKNOWN
  Set to ON
DEBUG:pybalboa.client:10.10.78.100 <- TOGGLE_STATE: 060abf110cda
DEBUG:pybalboa.client:10.10.78.100 -> STATUS_UPDATE: 20ffaf130003490e14002803060b0c000002000000000202490000001e0000a1
DEBUG:pybalboa.control:10.10.78.100 -- Blower 1 is now ON (1)
  State is now ON

DEBUG:pybalboa.client:10.10.78.100 -- disconnect requested
DEBUG:pybalboa.client:10.10.78.100 -- stopped listening
DEBUG:pybalboa.client:10.10.78.100 -- disconnected

Please add the above output to issue:

**Comment by superentwickler** [comment]
looks good. thank you
