### ISSUE TITLE
When no flow detected, the temp value is 127.5 degree

### ISSUE THREAD

**Issue by jurrianv** [garbled1/pybalboa#4]
When, there's no flow detected, the Balboa app shows --- as temperature value. In Home assistant I get the temperature 127.5. Is it possible to change this into ' ---'?
<img width="481" alt="Schermafbeelding 2020-07-09 om 21 53 20" src="https://user-images.githubusercontent.com/59375491/87084860-3401b500-c22f-11ea-979f-0bcd8e5ec18c.png">

**Comment by garbled1** [comment]
I'm curious here..  Mine absolutely doesn't do this..  I wonder where it's getting that value from..  Are the temperatures normal all other times?

**Comment by jurrianv** [comment]
Yes, all the temperatures are ok. Only when all the pumps are off (no flow) I'm getting this value. My spa app gives this screen: 
![IMG_8295](https://user-images.githubusercontent.com/59375491/87317061-cbfce880-c526-11ea-8536-d20d48daade3.jpg)

**Comment by garbled1** [comment]
huh.. thats totally crazy.  I'm guessing the spa app has special code that says if the temp is max-value or some specific insane number it prints ---.
I think the only thing I can do reasonably here, is not update the value when I get that specific insane number, and then have the homeassistant component note that the temp value is out of date....

Let me look at what would be required here.

**Comment by plmilord** [comment]
While parsing the incoming status update message, I fixed that issue like this:

`self.current_temp = byte_array[2] if (byte_array[2] != 255) else None`

...Then, Home Assistant will now also display ---

In Rest mode, the spa set the current temperature to 0xFF or 255 after a while. This is well documented in Balboa documentation and in this wiki: https://github.com/ccutrer/balboa_worldwide_app/wiki

You can have a look to my Home Assistant component code here: https://github.com/plmilord/Hass.io-custom-component-spaclient

**Comment by garbled1** [comment]
This is fixed in 0.12 and 0.5 of the component
