### ISSUE TITLE
Circulation Pump status wont toggle.

### ISSUE THREAD

**Issue by JayProtek** [garbled1/pybalboa#57]
******** Testing spa connection and configuration **********
Module identification
---------------------
MAC address: 00:15:27:71:f0:b2
iDigi Device Id: 00000000-00000000-001527FF-FF71F0B2
Device configuration
--------------------
Circulation pump: OFF
Pumps: ['Pump 1', 'Pump 2']
Lights: ['Light 1']
Aux: []
Blower: []
Mister: []
System information
------------------
Model: BP6013G1
Software version: M100_226 V37.0
Configuration signature: 1b456746
Current setup: 2
Voltage: None
Heater type: standard
DIP switch: 0000010000000000
Setup parameters
----------------
Min temps: ((50, 99), (10.0, 37.0))
Max temps: ((80, 104), (26.5, 40.0))
Pump count: 2
Filter cycle
------------
Filter cycle 1 start: 07:00:00
Filter cycle 1 duration: 1:00:00
Filter cycle 2 start: 16:00:00 (enabled)
Filter cycle 2 duration: 1:00:00
Status update
-------------
Temperature unit: CELSIUS
Temperature: 39.0
Target temperature: 39.0
Temperature range: HIGH
Heat mode: READY
Heat state: OFF
Pump status: [Pump 1: OFF, Pump 2: OFF]
Circulation pump: OFF
Light status: [Light 1: OFF]
Mister status: []
Aux status: []
Blower status: []
Spa time: 08:40 24hr
Filter cycle 1 running: False
Filter cycle 2 running: False
******** Testing spa controls **********
Temperature control
-------------------
Current target temperature: 39.0
  Set to 40.0
  Set temperature is now 40.0
Current target temperature: 40.0
  Set to 39.0
  Set temperature is now 39.0
Heat mode control
-----------------
Current state: READY
  Set to REST
  State is now REST
Current state: REST
  Set to READY
  State is now READY
Temperature range control
-------------------------
Current state: HIGH
  Set to LOW
  State is now LOW
Current state: LOW
  Set to HIGH
  State is now HIGH
Pump 1 control
--------------
Current state: OFF
  Set to ON
  State is now ON
Current state: ON
  Set to OFF
  State is now OFF
Pump 2 control
--------------
Current state: OFF
  Set to ON
  State is now ON
Current state: ON
  Set to OFF
  State is now OFF
Light 1 control
---------------
Current state: OFF
  Set to ON
  State is now ON
Current state: ON
  Set to OFF
  State is now OFF
Circulation pump control
------------------------
Current state: ON
  Set to OFF
  State was not changed after 10 seconds; is ON
Please add the above output to issue:
https://github.com/garbled1/pybalboa/issues/1
Process finished with exit code 0

I see that the call is to 003d for the circulation pump but cant see that in the documentation. The current status reads correctly if the pump is on or off it  just wont allow to toggle the status

**Comment by natekspencer** [comment]
I don't think it can be toggled. I need to adjust the test so it skips trying to control the circulation pump or emits a message saying that it is expected to fail.

**Comment by JayProtek** [comment]
Hi Mate,

Thanks for the quick response, Having looked at other blogs I believe you
are right that the circ pump does not allow for toggling kind of makes
sense really it's only needed for heating and filter cycles so no need to
control it.

Many thanks

Jason Richardson
*Managing Director*
*Tel: 07973624777*
